async function renderEmployees(){
const users=await getAll('users');
document.getElementById('empCount').textContent=users.filter(u=>u.role==='employee').length;
document.getElementById('adminCount').textContent=users.filter(u=>u.role==='admin').length;
document.getElementById('totalUsers').textContent=users.length;
document.getElementById('employeesTable').innerHTML=users.length?`<table><thead><tr><th>#</th><th>الاسم</th><th>اسم المستخدم</th><th>الصلاحية</th><th>تاريخ الإضافة</th><th>إجراءات</th></tr></thead><tbody>${users.map((u,i)=>`<tr><td class="text-slate-400 font-bold">${i+1}</td><td><div class="flex items-center gap-3"><div class="w-10 h-10 ${u.role==='admin'?'bg-amber-100 text-amber-700':'bg-blue-100 text-blue-700'} rounded-xl flex items-center justify-center font-black text-lg">${u.name.charAt(0)}</div><div class="font-bold text-slate-800">${u.name}</div></div></td><td class="text-slate-600 font-mono text-sm">${u.username}</td><td>${u.role==='admin'?'<span class="status-badge status-delivered">مدير</span>':'<span class="status-badge status-new">موظف</span>'}</td><td class="text-slate-400 text-sm">${formatDate(u.createdAt)}</td><td>${u.username!=='admin'?`<div class="flex gap-1.5"><button onclick="editEmployee(${u.id})" class="action-btn edit" title="تعديل"><i class="fas fa-edit"></i></button><button onclick="deleteEmployee(${u.id})" class="action-btn delete" title="حذف"><i class="fas fa-trash"></i></button></div>`:'<span class="text-slate-300 text-sm">المدير الرئيسي</span>'}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state"><i class="fas fa-users"></i><p>لا يوجد مستخدمين</p></div>';
}
function openEmployeeModal(){document.getElementById('employeeForm').reset();document.getElementById('empId').value='';document.getElementById('empModalTitle').textContent='إضافة موظف';openModal('employeeModal');}
async function editEmployee(id){const u=await getById('users',id);if(!u)return;document.getElementById('empId').value=u.id;document.getElementById('empName').value=u.name;document.getElementById('empUsername').value=u.username;document.getElementById('empPassword').value=u.password;document.getElementById('empRole').value=u.role;document.getElementById('empModalTitle').textContent='تعديل موظف';openModal('employeeModal');}
async function saveEmployee(e){e.preventDefault();const id=document.getElementById('empId').value;const data={name:document.getElementById('empName').value,username:document.getElementById('empUsername').value,password:document.getElementById('empPassword').value,role:document.getElementById('empRole').value,createdAt:new Date().toISOString()};if(id){data.id=parseInt(id);await putData('users',data);showToast('تم التحديث');}else{await addData('users',data);showToast('تم الإضافة');}closeModal('employeeModal');renderEmployees();}
async function deleteEmployee(id){if(!confirm('هل أنت متأكد؟'))return;await deleteData('users',id);showToast('تم الحذف');renderEmployees();}
